/* 공통 스크립트 include */
document.write('<script type="text/javascript" src="../../js/lib/jquery.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/bootstrap.min.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/bootstrap-datepicker.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/bootstrap-datepicker.ko.min.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/jquery.mCustomScrollbar.concat.min.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/jquery.twbsPagination.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/swiper.min.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/util.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/modal.js"></script>');
// document.write('<script type="text/javascript" src="../../js/lang/lang.js?'+(new Date())+'"></script>');
document.write('<script type="text/javascript" src="../../js/common_utils.js?'+(new Date())+'"></script>');
document.write('<script type="text/javascript" src="../../js/common.js?'+(new Date())+'"></script>');
document.write('<script type="text/javascript" src="../../js/study_utils.js?' + (new Date()) + '"></script>');
//document.write('<script type="text/javascript" src="../../js/common_p.js?'+(new Date())+'"></script>');
document.write('<script type="text/javascript" src="../../js/main_common.js?' + (new Date()) + '"></script>');
//document.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/aes.js"></script>');
document.write('<script type="text/javascript" src="../../js/common_kt.js"></script>');
document.write('<script type="text/javascript" src="../../js/lib/mode-ecb.js"></script>');
